apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: stock-simulator
    tier: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
    type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: stock-simulator
    tier: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: stock-simulator
    tier: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: stock-simulator
        tier: frontend
    spec:
      containers:
        - name: stock-client
          image: stock-client:latest
          ports:
            - containerPort: 3000
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "npm install && npm start"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: stock-simulator
    tier: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: stock-simulator
        tier: backend
    spec:
      containers:
        - name: stock-server
          image: stock-server:latest
          ports:
            - containerPort: 3000
