name: Test Python Backend
run-name: test-python-backend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: 3.10.11
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -e ./stock-server
        - name: Run tests
          working-directory: ./stock-server/src
          run: |
            python test.py
